version: '3.7'

services:
    backend:
        container_name: backend
        build:
            context: ./simple-api
            dockerfile: Dockerfile
        image: theoburdinat/myapi
        environment:
            DB_host: database
            DB_port: 5432
            DB_name: db 
            DB_user: theo
            DB_pass: pa$$
        networks:
            - app-network
        depends_on:
            - database

    database:
        container_name: database
        build:
            context: ./database
            dockerfile: Dockerfile
        image: theoburdinat/mydatabase
        environment:
            POSTGRES_USER: theo
            POSTGRES_PASSWORD: pa$$
        networks:
            - app-network
        volumes:
            - ./database/data:/var/lib/postgresql/data

    httpd:
        container_name: httpd
        build:
            context: ./httpd
            dockerfile: Dockerfile
        image: theoburdinat/myhttpd
        environment:
            BACKEND_HOST: backend
            FRONTEND_HOST: frontend
        ports:
            - "80:80"
        networks:
            - app-network
        depends_on:
            - backend

    frontend:
        container_name: frontend
        build:
            context: ./devops-front
            dockerfile: Dockerfile
        image: theoburdinat/myfrontend
        env: 
            host: localhost
        networks:
            - app-network
        depends_on:
            - backend
            - database

networks:
    app-network:

volumes:
    data:

