version: '3.7'

services:
    backend:
        container_name: backend
        build:
            context: ./API/simple-api-student
            dockerfile: Dockerfile
        image: theoburdinat/myapi
        environment:
            DB_host: database
            DB_port: 5432
            DB_name: db 
            DB_user: theo
            DB_pass: pa$$
        networks:
            - app-network
        depends_on:
            - database

    database:
        container_name: database
        build:
            context: ./postgres
            dockerfile: Dockerfile
        image: theoburdinat/mydatabase
        environment:
            POSTGRES_USER: theo
            POSTGRES_PASSWORD: pa$$
        networks:
            - app-network
        volumes:
            - ./postgres/data:/var/lib/postgresql/data

    httpd:
        container_name: httpd
        build:
            context: ./HTTP
            dockerfile: Dockerfile
        image: theoburdinat/myhttpd
        environment:
            BACKEND_HOST: backend
        ports:
            - "80:80"
        networks:
            - app-network
        depends_on:
            - backend

networks:
    app-network:

volumes:
    data:

