name: CI Build and Push Docker Image

on:
  workflow_run:
    workflows: ["CI Test Backend"]
    types:
      - completed

jobs:
  build-and-push-docker-image:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest tag
        id: get_latest
        run: echo "LATEST_TAG=$(curl -s https://hub.docker.com/v2/repositories/${{ secrets.DOCKERHUB_USERNAME }}/myapi/tags/?page_size=1 | jq -r '.results[0].name')" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          LATEST_TAG=${{ env.LATEST_TAG }}
          if [[ "$LATEST_TAG" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            IFS='.' read -r -a PARTS <<< "${LATEST_TAG:1}"
            PARTS[2]=$((PARTS[2] + 1))
            NEW_TAG="v${PARTS[0]}.${PARTS[1]}.${PARTS[2]}"
          else
            NEW_TAG="v1.0.0"
          fi
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          echo "New version tag: $NEW_TAG"

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: ${{secrets.DOCKERHUB_USERNAME}}/myapi:${{ env.NEW_TAG }}
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{secrets.DOCKERHUB_USERNAME}}/mydatabase:${{ env.NEW_TAG }}
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./httpd
          tags: ${{secrets.DOCKERHUB_USERNAME}}/myhttpd:${{ env.NEW_TAG }}
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./devops-front
          tags: ${{secrets.DOCKERHUB_USERNAME}}/myfrontend:${{ env.NEW_TAG }}
          push: ${{ github.ref == 'refs/heads/main' }}
