name: CD on takima server with Ansible

on: 
    workflow_run:
        workflows: ["CI Build and Push Docker Image"]
        types:
          - completed

jobs:
    deployment:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - name: Install Ansible
              run: |
                  python -m pip install --upgrade pip
                  pip install ansible
            - name: Deploy
              run: |
                  ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml
            

        