name: CD on takima server with Ansible

on: 
    workflow_run:
        workflows: ["CI Build and Push Docker Image"]
        types:
          - completed

jobs:
    deployment:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2.5.0
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.x'
            - name: Install Ansible
              run: |
                  python -m pip install --upgrade pip
                  pip install ansible
            # - name: Move SSH key
            #   run: |
            #       mkdir -p ~/.ssh
            #       echo "${{ secrets.SSH_SERVER_KEY }}" > ~/.ssh/id_rsa
            #       chmod 600 ~/.ssh/id_rsa
            #       cat ~/.ssh/id_rsa

            - name: SSH
              uses: webfactory/ssh-agent@v0.5.3  # Use the webfactory/ssh-agent action to set up SSH
              with:
                ssh-private-key: ${{ secrets.SSH_SERVER_KEY }} 
              
            - name: Add SSH known hosts
              run: |
                mkdir -p ~/.ssh
                ssh-keyscan -H remy.francis.takima.cloud >> ~/.ssh/known_hosts
              
            - name: Deploy
              run: |
                  ansible-playbook -i ansible/inventories/setup.yml ansible/playbook.yml



        